### ISSUE TITLE
pred errors

### ISSUE THREAD

**Issue by relaxtakenotes** [relaxtakenotes/zipline#2]
do everything on the client too

**Comment by relaxtakenotes** [comment]
solved it to the best of my capability, at least it's not that bad anymore

**Comment by datae-git** [comment]
Did you forget to push your update? the client isn't predicting anything and it's still the server doing everything

**Comment by relaxtakenotes** [comment]
the only change was setting the origin on the client too because otherwise client thought it was falling, didnt do anything else

**Comment by relaxtakenotes** [comment]
mayb will try to tackle it properly tmrw
