### ISSUE TITLE
Shaking and damage while riding on cable

### ISSUE THREAD

**Issue by kakahost** [relaxtakenotes/zipline#5]
Also, i can't climb on zipline normally
[https://youtu.be/fEi3GZntXaQ](url)

**Comment by relaxtakenotes** [comment]
Avoid playing with this mod on multiplayer servers. You're getting prediction errors and I haven't setup anything to combat it yet. I'm currently in a process of rewriting the whole logic in this mod so it works better.

**Comment by relaxtakenotes** [comment]
Oh, by the way, you couldn't get on the zipline because the trace between the rope start and your origin failed, I guess there was just some tiny little obstacle that got in the way.
