### ISSUE TITLE
It wont get me on the zipline 

### ISSUE THREAD

**Issue by Anti-water-Baja** [relaxtakenotes/zipline#8]
the errors i got were 
displayed as other
[ERROR] lua/autorun/server/sv_zipline.lua:77: bad argument #1 to 'Distance' (Vector expected, got nil)
  1. Distance - [C]:-1
   2. __event - lua/autorun/server/sv_zipline.lua:77

[ERROR] lua/autorun/server/sv_zipline.lua:63: bad argument #1 to 'Distance' (Vector expected, got nil)
  1. Distance - [C]:-1
   2. __event - lua/autorun/server/sv_zipline.lua:63
displayed as zipline

[Ziplines] lua/autorun/server/sv_zipline.lua:77: bad argument #1 to 'Distance' (Vector expected, got nil)
    1. Distance - [C]:-1
        2. v - lua/autorun/server/sv_zipline.lua:77
            3. unknown - lua/autorun/hook_inspector.lua:229

**Comment by relaxtakenotes** [comment]
fixed
